name: geo-env
channels:
  - conda-forge
dependencies:
  # - cartopy
  # - datapane
  - gdal
  - geemap>=0.11.2
  - geopandas
  # - imageio
  - jupyter-server-proxy
  # - keplergl
  - leafmap>=0.7.6
  - localtileserver>=0.4.3
  # - osmnx
  - pip
  # - pydeck
  # - pydeck-earthengine-layers
  - python>=3.8
  - requests
  # - rio-cogeo
  # - tifffile
  # - xarray_leaflet
  - pip:
      # - git+https://github.com/banesullivan/localtileserver
      # - git+https://github.com/giswqs/leafmap
      # - git+https://github.com/giswqs/geemap 
